### ISSUE TITLE
False positive while detecting inline signature

### ISSUE THREAD

**Issue by lucas8** [jkraemer/mail-gpg#22]
When detecting inline signatures, signed_inline? only checks if `-----BEGIN PGP SIGNED MESSAGE-----` is present, but I came across mail where it was present in the citation of a previous mail, thus wrongly marking the mail as signed.
An easy fix would be to simply check if `-----BEGIN PGP SIGNED MESSAGE-----` is present at the begginning of a line. I would have proposed a patch, but my knowledge of ruby is nearly inexistent.

**Comment by jkraemer** [comment]
good point, thanks for reporting!
