### ISSUE TITLE
Changing the attachment filename (encrypted.asc)

### ISSUE THREAD

**Issue by chrislewis60** [jkraemer/mail-gpg#25]
This is a question/feature request ... 

Is there any scope for changing the filename used as the encrypted attachment - currently 'encrypted.asc'? It looks fairly hard coded within EncryptedPart class - is that deliberately so? For example, could a timestamp be added so it became '2015.08.14-020312_encrypted.asc' or even be able to add in another unique ID to the name. I've potentially got quite a lot of encrypted attachments to deal with and a way to distinguish them without revealing anything about what's inside the message would be useful. Thanks.

**Comment by jkraemer** [comment]
see #26
