### ISSUE TITLE
Unexpected encryption

### ISSUE THREAD

**Issue by robsdedude** [jkraemer/mail-gpg#31]
Hi,

I have mailers that look like that:

```
class TabMailer < ActionMailer::Base
    def tab_email(tab)
        @user = tab.user
        @tab = tab
        to = get_email_with_name(@user)
        mail(
            from: 'sender@example.com',
            to: to,
            subject: 'Some subject',
            gpg: {
                encrypt: !!@user.pgp_key,
                keys: {
                    @user.email => @user.pgp_key
                }
            })
    end
end
```

each `tab` is guaranteed to have a `user`. But not every `user` has the `pgp_key` field filled. What happens is, that some users (not all) that don't have a `pgp_key` get an encrypted mail anyway. The keys used for encryption of those mails are all keys in the database together. I can't reproduce this behavior in development environment. Any idea what that issue comes from?

**Comment by roba91** [comment]
Ok, so I found out, that on the productive system (not on my dev system) your gem accepts empty strings as a key. And given an empty string as key it uses all keys (the key ring was probably auto filled with the other keys used) to encrypt the message. So it seems like the some Linux packages are handling things oddly.

**Comment by robsdedude** [comment]
I think this all boils down to a feature request
