### ISSUE TITLE
Still interested in this project?

### ISSUE THREAD

**Issue by duckdalbe** [jkraemer/mail-gpg#36]
@jkraemer I'm wondering if you're still interested in maintaining this library. You hardly reply or show other activity since month.

Version 3 of Schleuder, the crypto mailing list manager <https://codecoop.org/schleuder/schleuder3>, is depending on mail-gpg and is bound to be released soon. But I need e.g. #35 resolved for that.

I'd rather like to find a cooperative solution than forking, but ultimately I'd have to do it if nothing happens.

Alternatively we could maybe share maintenance? Or will you come back from silence some time soon?

In any case I'd like to again say: Thanks for your work! You made my life easier!

**Comment by jkraemer** [comment]
thanks for your PR, I just merged it and will release a new gem version now.

**Comment by duckdalbe** [comment]
Great, thank you!
