### ISSUE TITLE
Hkp#search fails for uris with url scheme hkp

### ISSUE THREAD

**Issue by nhoffmann** [jkraemer/mail-gpg#39]
When I try to search on a keyserver with url scheme `hkp` I get a `No such file error`. I think that is due to mail-gpg's `Hkp` class using `open-uri` under the hood, which only works with `http`, `https` and `ftp` (please correct me if I'm wrong).

Steps to reproduce:

    hkp = Hkp.new("hkp://keys.gnupg.net")
    hkp.search(email)
    Errno::ENOENT: No such file or directory @ rb_sysopen - hkp://keys.gnupg.net/pks/lookup?options=mr&search=...

It works when providing the same host and path but with url scheme `http` (e.g. "http://keys.gnupg.net"). 

I got really confused, because the `README` has a `hkp` url in the Key lookup example. 

I would be happy to provide a fix, either as an update to the `README` or improving the `Hkp` class, but wanted to get your guys opinions first. Also, please enlighten me if I got it all wrong 😅

**Comment by jkraemer** [comment]
please check out my latest commit, this should be fixed now.

**Comment by nhoffmann** [comment]
@jkraemer Thank you very much for the fix. Can you tell me when there will be a new release of this gem that includes the fix? Thanks again.

**Comment by duckdalbe** [comment]
I'd also love to see a new release.
