### ISSUE TITLE
Releases: Please provide signatures

### ISSUE THREAD

**Issue by ge-fa** [jkraemer/mail-gpg#41]
As announced, I've [packaged](https://packages.debian.org/sid/ruby-mail-gpg) mail-gpg for Debian. For further releases, I really would like to be sure to pull in code which wasn't tampered along the way. Would it be possible for you to provide signatures for the releases? [Here](https://wiki.debian.org/Creating%20signed%20GitHub%20releases) are some information about the workflow involved. 

TIA and for your work!

**Comment by jkraemer** [comment]
I just released 0.3.0, following the guiode you linked to. Can you please have a look if that worked out?

**Comment by ge-fa** [comment]
Thanks! Works as expected!
