### ISSUE TITLE
Strip "headers" from clearsigned inline messages

### ISSUE THREAD

**Issue by duckdalbe** [jkraemer/mail-gpg#42]
In InlineSignedMessage#strip_inline_signature() mail-gpg strips the signature and adds an end-of-signed-text-marker.

In my opinion it should also remove the optional OpenPGP-"headers" that may follow the begin-of-signed-text-marker, like these:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512
```

If I understand the idea correctly it is meant to help identifying which section of the text was actually signed. The "headers" are meta-data that don't help humans, but only irritate them. They should be stripped, too.

If you agree I could look into implementing this.

**Comment by jkraemer** [comment]
Yeah, that looks like a good idea to me...
