### ISSUE TITLE
Properly handle "inline"-encrypted multipart/alternative

### ISSUE THREAD

**Issue by duckdalbe** [jkraemer/mail-gpg#49]
Several tools, e.g. Mailvelope, produce multipart/alternative-messages in which both parts contain the ciphertext; and in the html-part it's enclosed in a little HTML.

Example:

```mail
Content-Type: multipart/alternative; boundary="94eb2c074e843f8e250550e728d4"

--94eb2c074e843f8e250550e728d4
Content-Type: text/plain; charset="UTF-8"

-----BEGIN PGP MESSAGE-----
Version: Mailvelope v1.7.2
Comment: https://www.mailvelope.com

wcFMA2zW/XKwDLjKAQ//eVs/Ng+IcfUt+QuYLHZbZAsKwD9qhXs06DWRh6zY
1sO2hI59CMvoZ1P+DzMOPBqpBmQ438y3+kxEzOJVh1KxKJukFEv39m/QZDOk
[...]
j15W9B36eQcqqwz9MJ53/V0k5kvGiTTdQt+tH09+NwMHSjQVBFrhat8bVCdM
K3GxDIArXwi/yxRdg0IEqBdZvBxzcL8A3JVS0xzuOUXiErcQ5jTRt9IaiM/d
=wXg6
-----END PGP MESSAGE-----

--94eb2c074e843f8e250550e728d4
Content-Type: text/html; charset="UTF-8"

<div dir="ltr"><pre>-----BEGIN PGP MESSAGE-----
Version: Mailvelope v1.7.2
Comment: <a href="https://www.mailvelope.com">https://www.mailvelope.com</a>

wcFMA2zW/XKwDLjKAQ//eVs/Ng+IcfUt+QuYLHZbZAsKwD9qhXs06DWRh6zY
1sO2hI59CMvoZ1P+DzMOPBqpBmQ438y3+kxEzOJVh1KxKJukFEv39m/QZDOk
[...]
j15W9B36eQcqqwz9MJ53/V0k5kvGiTTdQt+tH09+NwMHSjQVBFrhat8bVCdM
K3GxDIArXwi/yxRdg0IEqBdZvBxzcL8A3JVS0xzuOUXiErcQ5jTRt9IaiM/d
=wXg6
-----END PGP MESSAGE-----
<pre></pre></pre></div>

--94eb2c074e843f8e250550e728d4--
```
gpgme chokes on the html-part when mail-gpg tries to decrypt the body (`GPGME::Error::NoData`).

In my eyes it's mail-gpg's reponsibility to find decryptable ciphertext or deal with non-decipherable parts. But should undecryptable ciphertexts be stripped? Or be left untouched in the mime-structure? And how to communicate the failed attempt to the calling code?

A little fix that just leave mime-parts of type 'text/html' alone is already done. If you would like it as a pull request, please let me know.

**Comment by duckdalbe** [comment]
I just noticed that mail-gpg inconsistently checks for inline-pgp-data.

In `encrypted_inline?` it uses
```ruby
part.body.include?('-----BEGIN PGP MESSAGE-----')
```

In `signed_inline?` it uses
```ruby
mail.body.to_s =~ /^-----BEGIN PGP SIGNED MESSAGE-----/
```

The latter check doesn't match the HTML-wrapped inline-ciphertext, so signed-but-unencrypted messages are not affected.

The previously reported bug could also be "solved" by strickter checking for inline-ciphertext. mail-gpg would then claim that such a message is not encrypted — that's not really correct, but at least it wouldn't raise exceptions.

**Comment by duckdalbe** [comment]
> A little fix that just leave mime-parts of type 'text/html' alone is already done. If you would like it as a pull request, please let me know.

Are you not interested or did you just miss this?

**Comment by jkraemer** [comment]
I missed that. Please go ahead with the PR :)

**Comment by jkraemer** [comment]
thanks for the PR!
