### ISSUE TITLE
Shouldn't the Gemfile have a dependency on gpgme?

### ISSUE THREAD

**Issue by kernelsmith** [jkraemer/mail-gpg#68]
I was researching the idea that GnuPG (starting with 2.1 apparently) sort of got rid of `passphrase_callback`
https://stackoverflow.com/questions/35064312/why-does-gpgme-gnupg-use-pinentry-for-password-input tho it appears to me that gpgme and the gpgme gem still seem to support it

my googling led me to your repo and you mention in the README that you can use passphrase_callback

```Ruby
gpg encrypt: true, sign_as: 'joe@otherdomain.com',
      passphrase_callback: ->(obj, uid_hint, passphrase_info, prev_was_bad, fd){puts "Enter passphrase for #{passphrase_info}: "; (IO.for_fd(fd, 'w') << readline.chomp).flush }
end.deliver
```
So then I wondered what gpgme gem version the mail-gpg gem could support, but I didn't see any references to the gpgme gem. This is just a long-winded way of saying, shouldn't you have a gem dependency on gpgme in Gemfile (regardless of whether they're getting rid of passphrase_callback) LOL.

**Comment by jkraemer** [comment]
the `gemspec` line in the Gemfile basically includes dependencies listed in the gem specification, and this has the gpgme dependency listed:

https://github.com/jkraemer/mail-gpg/blob/1c77be4fe58273b489faa0b79dc6937f07c77f61/mail-gpg.gemspec#L22

**Comment by kernelsmith** [comment]
Aaaassand I'm a moron. Sorry for the noise
